CREATE DATABASE Auction;

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "ADDRESS" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "STREET" varchar(100) NOT NULL,
    "NUMBER" varchar(10),
    "DISTRICT" varchar(100) NOT NULL,
    "CEP" varchar(8) NOT NULL,
    "CITY" varchar(100) NOT NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_ADDRESS" PRIMARY KEY ("Id")
);

CREATE TABLE "AUCTION" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NAME" varchar(100) NOT NULL,
    "START_AT" timestamp without time zone NOT NULL,
    "END_AT" timestamp without time zone NOT NULL,
    "ACTIVE" boolean NOT NULL DEFAULT TRUE,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_AUCTION" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "ITEM" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NAME" VARCHAR(100) NOT NULL,
    "DESCRIPTION" VARCHAR(500),
    "BRAND" VARCHAR(100) NOT NULL,
    "TYPE" integer NOT NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_ITEM" PRIMARY KEY ("Id")
);

CREATE TABLE "PARTICIPANT" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NAME" varchar(100) NOT NULL,
    "EMAIL" varchar(100) NOT NULL,
    "ADDRESS_ID" integer NOT NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_PARTICIPANT" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PARTICIPANT_ADDRESS_ADDRESS_ID" FOREIGN KEY ("ADDRESS_ID") REFERENCES "ADDRESS" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AUCTION_ITEM" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AUCTION_ID" integer NOT NULL,
    "ITEM_ID" integer NOT NULL,
    "MINIMUM_BID" numeric(10,2),
    "CURRENT_VALUE" numeric(10,2),
    "START_AT" time without time zone NOT NULL,
    "END_AT" time without time zone NOT NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_AUCTION_ITEM" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AUCTION_ITEM_AUCTION_AUCTION_ID" FOREIGN KEY ("AUCTION_ID") REFERENCES "AUCTION" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AUCTION_ITEM_ITEM_ITEM_ID" FOREIGN KEY ("ITEM_ID") REFERENCES "ITEM" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BID" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PARTICIPANT_ID" integer NOT NULL,
    "AUCTION_ITEM_ID" integer NOT NULL,
    "VALUE" numeric(10,2) NOT NULL,
    "WINNER" boolean NOT NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_BID" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BID_AUCTION_ITEM_AUCTION_ITEM_ID" FOREIGN KEY ("AUCTION_ITEM_ID") REFERENCES "AUCTION_ITEM" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BID_PARTICIPANT_PARTICIPANT_ID" FOREIGN KEY ("PARTICIPANT_ID") REFERENCES "PARTICIPANT" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AUCTION_ITEM_AUCTION_ID" ON "AUCTION_ITEM" ("AUCTION_ID");

CREATE UNIQUE INDEX "IX_AUCTION_ITEM_ITEM_ID" ON "AUCTION_ITEM" ("ITEM_ID");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_BID_AUCTION_ITEM_ID" ON "BID" ("AUCTION_ITEM_ID");

CREATE INDEX "IX_BID_PARTICIPANT_ID" ON "BID" ("PARTICIPANT_ID");

CREATE UNIQUE INDEX "IX_PARTICIPANT_ADDRESS_ID" ON "PARTICIPANT" ("ADDRESS_ID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240114152710_FinalVersion', '8.0.1');

COMMIT;